language: php
php:
- 7.4
cache:
  directories:
  - $HOME/.composer/cache/files
install:
- composer install --prefer-dist
before_script:
- chmod +x vendor/bin/phpunit
- phpenv config-rm xdebug.ini
- cp .env.example .env
- php artisan key:generate
script:
- composer test
notifications:
  email: false
  slack:
    secure: my-slack-token
